export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const TOGGLE_EDIT_TODO = 'TOGGLE_EDIT_TODO';
export const EDIT_TODO = 'EDIT_TODO';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const PENDING_REQUEST = 'PENDING_REQUEST';
export const RECEIVE_TODOS = 'RECEIVE_TODOS'; 